export const DASHBOARD_CSS = `
html{color-scheme:dark;scroll-behavior:smooth}
body{background:#090d0c;font-size:14px;isolation:isolate}
button,input,select{font:inherit}button,a,input,select{-webkit-tap-highlight-color:transparent}button{transition:background .18s,border-color .18s,transform .18s}button:disabled{opacity:.45;cursor:wait}
.ambient{position:fixed;inset:0;z-index:-1;overflow:hidden;pointer-events:none;background:radial-gradient(ellipse at 80% 0%,#17342855,transparent 65%),#090d0c}
.ambient::before,.ambient::after{content:'';position:absolute;width:85vw;height:75vh;left:-20%;top:-30%;border-radius:45%;background:radial-gradient(ellipse,#33734f77,transparent 65%);animation:aurora-drift 28s ease-in-out infinite alternate;will-change:transform}
.ambient::after{left:45%;top:35%;background:radial-gradient(ellipse,#41608033,transparent 65%);animation-delay:-14s;animation-duration:35s}
.ambient[data-scene=ember]::before{background:radial-gradient(ellipse,#b8653544,transparent 65%)}.ambient[data-scene=ember]::after{background:radial-gradient(ellipse,#79505444,transparent 65%)}
.ambient[data-scene=ocean]::before{background:radial-gradient(ellipse,#258c9255,transparent 65%)}.ambient[data-scene=ocean]::after{background:radial-gradient(ellipse,#4157a544,transparent 65%)}
.ambient[data-scene=off]{background:#090d0c}.ambient[data-scene=off]::before,.ambient[data-scene=off]::after{display:none}
@keyframes aurora-drift{to{transform:translate(18vw,16vh) rotate(35deg) scale(1.2)}}
.nv{height:76px;padding:0 max(28px,calc((100vw - 1380px)/2));background:#090d0ce8;border-bottom:1px solid #ffffff0d;gap:44px;backdrop-filter:blur(18px)}
.nb{font-size:19px;letter-spacing:.12em}.nl{gap:6px}.nk{font-size:12px;padding:10px 14px;border-radius:8px}.nk.a{background:#ffffff08;color:#d9f8df}.nr{gap:10px}.lamp{font-size:9px;letter-spacing:.12em;border-radius:20px;padding:5px 9px}.lamp.on{box-shadow:none;background:#1ed76015;color:var(--ac);border-color:#1ed76035}.st{font-size:11px}.dot{width:6px;height:6px}
.mn{max-width:1380px;padding:34px 28px 48px}.page-intro{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:28px}.eyebrow{font:10px var(--mn);letter-spacing:.2em;text-transform:uppercase;color:#92aa9a;margin-bottom:9px}.page-intro h1{font-size:clamp(25px,3vw,36px);font-weight:500;letter-spacing:-1.4px;color:#f4f1e8}.page-intro h1 span{color:#8b9b90}.intro-note{margin-top:8px;font-size:12px;color:#95a299}.scene-tools{display:flex;align-items:center;gap:8px;flex-wrap:wrap;font-size:11px;color:var(--dm)}.scene-tools select{background:#121b16;border:1px solid #ffffff16;color:#d2ded5;padding:9px 26px 9px 10px;border-radius:8px;max-width:150px}.scene-tools button{background:#121b16;border:1px solid #ffffff16;color:#d2ded5;padding:9px 12px;border-radius:8px;cursor:pointer}
.g{grid-template-columns:minmax(0,1.2fr) minmax(0,1fr) minmax(280px,.85fr);gap:18px;align-items:start}.g>.cd{min-width:0}.cd{background:#111914ed;border:1px solid #ffffff10;border-radius:16px;padding:22px;box-shadow:0 8px 32px #00000012}.ct{font-size:10px;letter-spacing:.14em;color:#c0cec4;margin-bottom:20px}.ct .rv{font-size:10px;color:#91a497}.section-no{color:#8a9e90;margin-right:9px;font:10px var(--mn)}
.player-card{grid-column:1/3;grid-row:1;position:relative;overflow:hidden;min-height:368px;background:linear-gradient(125deg,#1c2c21f2,#111914f5 65%)}.queue-card{grid-column:3;grid-row:1/3;align-self:stretch}.request-card{grid-column:1/3;grid-row:2}.sound-card{grid-column:1;grid-row:3}.discovery-card{grid-column:2;grid-row:3}.server-card{grid-column:3;grid-row:3}.chat-card{grid-column:1/3}.system-card{grid-column:3}.errors-card{grid-column:1/-1}
.deck{display:grid;grid-template-columns:190px minmax(0,1fr);column-gap:28px;align-items:center;background:none;border:0;box-shadow:none;padding:0;margin:12px 0 26px}.record-stage{grid-row:1/5;width:190px;height:190px;position:relative;display:grid;place-items:center}.record{width:174px;height:174px;border-radius:50%;background:repeating-radial-gradient(circle at center,#151918 0 1px,#232b24 2px,#101411 3px,#171d18 4px);border:1px solid #354238;box-shadow:0 12px 35px #0009,inset 0 0 0 5px #0c100d;position:relative;animation:record-spin 18s linear infinite;animation-play-state:paused}.record::before{content:'';position:absolute;inset:0;border-radius:50%;background:conic-gradient(from 25deg,transparent,#cedbd61c 30deg,transparent 70deg,transparent 180deg,#cedbd620 210deg,transparent 255deg)}.record-label{position:absolute;inset:54px;border-radius:50%;background:#bad4a8;display:flex;flex-direction:column;align-items:center;justify-content:center;color:#1d3828;font:8px var(--mn);letter-spacing:1px;box-shadow:0 0 0 4px #080c0999}.record-label b{font-size:22px;margin-bottom:1px}.record-label::after{content:'';width:6px;height:6px;border-radius:50%;background:#101811;margin-top:6px}.record-stage::after{content:'';position:absolute;right:1px;top:10px;width:5px;height:100px;background:linear-gradient(90deg,#55695b,#b0b9ae,#4b5f50);transform:rotate(-22deg);transform-origin:top;border-radius:5px;box-shadow:3px 4px 5px #0005}.player-card[data-playing=true] .record{animation-play-state:running}@keyframes record-spin{to{transform:rotate(360deg)}}
.ns{font-size:9px;letter-spacing:.2em;margin-bottom:12px;display:flex;align-items:center;gap:8px}.ns::before{content:'';width:5px;height:5px;border-radius:50%;background:currentColor}.nt{font-size:clamp(24px,2.8vw,38px);line-height:1.15;letter-spacing:-1.2px;font-weight:500;color:#f6f2e8;white-space:normal;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;overflow-wrap:anywhere}.track-detail{font-size:12px;color:#9bae9e;line-height:1.6;margin:10px 0 14px;min-height:19px}.progress-block{grid-column:2}.tm{font-size:10px;margin:10px 0 0;color:#b5c9bc}.sk{height:5px;border:0;background:#ffffff15;border-radius:4px;overflow:visible}.skf{border-radius:4px;background:#bdd6a9}.skf::after{content:'';position:absolute;right:-3px;top:-2px;width:9px;height:9px;border-radius:50%;background:#d6edc4}.tp{gap:10px;border-top:1px solid #ffffff0b;padding-top:20px}.tb{height:38px;width:38px;border:0;border-radius:50%;box-shadow:none;background:transparent;font-size:16px;color:#b0c3b5}.tb:hover{background:#ffffff0b}.tb.main{height:48px;width:48px;background:#d0e6b9;color:#18251a;font-size:18px}.tb.dng{color:#b0c3b5}.vg{gap:10px}.vg .vv{color:#b0c3b5;font-size:10px}.vg input[type=range]{width:90px}.volume-label{font:9px var(--mn);letter-spacing:.1em;color:#91a497}.player-links{margin-left:14px;display:flex;gap:8px}.player-links .ch{background:none;border-color:#ffffff14}
.request-card{padding:18px 22px}.request-card .ct{margin-bottom:12px}.ir{gap:8px}.ir input{background:#080f0b80;border-color:#ffffff12;padding:12px 14px;border-radius:9px;font-size:12px}.go{background:#c9e3b2;color:#19271c;font-size:11px;padding:12px 20px;border-radius:9px}.nx{font-size:10px;margin-top:10px}.nx input{width:13px;height:13px}.queue-card .ql{max-height:345px;min-height:270px}.queue-card .qi{padding:15px 0;gap:10px;flex-wrap:wrap;border-color:#ffffff09}.queue-card .qn{font-size:10px;min-width:18px}.queue-card .qt{font-size:12px;line-height:1.5;flex-basis:calc(100% - 90px);white-space:normal;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical}.queue-card .qr{font-size:10px;margin-left:28px;max-width:90%;order:2;color:#8d9f93}.qx{border:0;background:#ffffff05;color:#93a499;width:30px;height:30px;border-radius:7px}.queue-footer{border-top:1px solid #ffffff0c;margin-top:16px;padding-top:16px;display:flex;justify-content:space-between;gap:8px}.queue-footer .ch{font-size:10px}.em{font-size:12px;color:#91a497;line-height:1.7;padding:22px 10px}.empty-mark{font-size:30px;color:#64836e;display:block;margin-bottom:10px}
.sg{border-color:#ffffff12;background:#080f0b70;border-radius:8px}.sg button{font-size:9px;padding:10px 4px;letter-spacing:.07em}.sg button.on{background:#bdd6a9;color:#1b2d21}.sw{padding:11px 10px;background:#0a120d66;border-color:#ffffff0d;font-size:11px;border-radius:8px}.sw.on{border-color:#7da77f;color:#d7e8d8}.sw .led{height:5px;width:5px}.sw.on .led{box-shadow:none}.ch{font-size:10px;padding:7px 10px;background:#0a120d66;border-color:#ffffff10;border-radius:7px}.fc{gap:7px}.discovery-card .ir{margin-top:12px}.discovery-card .ir input{width:100%;padding:10px}.discovery-card .go{padding:10px}.mini-label{font:9px var(--mn);text-transform:uppercase;letter-spacing:.13em;color:#91a497;margin:20px 0 10px}.helper{font-size:11px;line-height:1.7;color:#91a497}.discovery-card .sg{margin:12px 0}.server-card #srvTree{max-height:290px;overflow:auto}.chrow{background:#0a120d66;border-color:#ffffff0c;padding:11px;border-radius:8px}.chrow.here{background:#1c332288;border-color:#62856a55}.chnm{font-size:11px}.users li{font-size:10px;line-height:1.7}.botpill{font-size:8px;letter-spacing:.08em;background:#bdd6a9}.chct{font-size:9px}.chat-card .ql{min-height:100px}.chat-card .qi{font-size:11px;line-height:1.6;border-color:#ffffff09;padding:9px 0;flex-wrap:wrap}.chat-card .qn{font-size:9px}.chat-card .cmt{flex-basis:55%}.cnm{color:#c1d8b2}.cmB{color:#91bda2}.sg3{gap:8px}.stt{border:0;background:#080f0b70;border-radius:9px;padding:16px 4px}.sv{font-size:19px}.sv.am{color:#bdd6a9}.sl{font-size:8px;letter-spacing:.1em}.system-card .ct .rv{font-size:9px}.errors-card .ct{margin-bottom:8px}.errors-card .em{text-align:left;padding:8px 0}.dw{background:#080f0b;color:#c4d4c9;border-color:#ffffff0e}.page-footer{display:flex;justify-content:space-between;gap:16px;color:#718679;font:9px var(--mn);letter-spacing:.1em;padding-top:12px}.page-footer a{color:#a6bcad;text-decoration:none}.toast{background:#17251d;border-color:#375b42;color:#eff4eb;font-size:12px}
html[data-motion=paused] *,html[data-motion=paused] *::before,html[data-motion=paused] *::after{animation-play-state:paused!important}
@media(min-width:1500px){.mn{padding-top:44px}.deck{column-gap:38px}.player-card{padding:26px}}
@media(max-width:1050px){.g{grid-template-columns:minmax(0,1fr) minmax(0,1fr)}.player-card,.request-card{grid-column:1/-1;grid-row:auto}.queue-card,.sound-card,.discovery-card,.server-card,.chat-card,.system-card{grid-column:auto;grid-row:auto}.queue-card{grid-row:3/5}.chat-card{grid-column:1/-1}.system-card{grid-column:1/-1}.queue-card .ql{max-height:500px}.nv{gap:24px;padding:0 24px}.nr .st{display:none}}
@media(max-width:640px){.nv{height:auto;min-height:64px;flex-wrap:wrap;gap:12px;padding:16px 18px 0}.nb{font-size:16px}.nr{order:1}.nl{order:2;width:100%;justify-content:space-between;padding:0 0 10px;gap:0}.nk{font-size:11px;padding:8px 10px}.mn{padding:25px 16px}.page-intro{align-items:flex-start;flex-direction:column;gap:18px;margin-bottom:22px}.page-intro h1{font-size:30px}.scene-tools{width:100%;justify-content:flex-end}.scene-tools label{margin-right:auto}.g{grid-template-columns:minmax(0,1fr);gap:14px}.g>.cd{grid-column:1;grid-row:auto}.cd{padding:18px}.deck{grid-template-columns:90px minmax(0,1fr);column-gap:16px;margin:20px 0}.record-stage{width:90px;height:100px}.record{width:88px;height:88px}.record-label{inset:28px;font-size:4px;letter-spacing:0}.record-label b{font-size:11px}.record-label::after{width:3px;height:3px;margin-top:2px}.record-stage::after{height:50px;width:3px;top:4px;right:0}.nt{font-size:25px;letter-spacing:-.7px}.ns{font-size:8px;margin-bottom:8px}.track-detail{font-size:10px;margin:8px 0}.progress-block{grid-column:1/-1;margin-top:22px}.player-card{min-height:0}.tp{gap:6px;padding-top:16px}.tb{width:32px;height:36px}.tb.main{width:43px;height:43px}.player-links{margin-left:auto}.vg{width:100%;justify-content:flex-end;margin-top:12px;padding-top:12px;border-top:1px solid #ffffff0b}.vg input[type=range]{width:130px}.volume-label{margin-right:auto}.queue-card .ql{min-height:0;max-height:320px}.ir input{font-size:12px}.go{padding:12px}.page-footer{font-size:8px;line-height:1.8}.scene-tools select,.scene-tools button{min-height:36px}.qx{width:36px;height:36px}.ch{min-height:32px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.ambient::before,.ambient::after,.record{animation:none!important}}
`;

export const AMBIENCE_JS = `
function setScene(value){
  if(['aurora','ember','ocean','off'].indexOf(value)<0)value='aurora';
  document.getElementById('ambient').setAttribute('data-scene',value);
  document.getElementById('scene').value=value;
  try{window.localStorage.setItem('rhapsod.scene',value);}catch(e){}
}
var motionPaused=false;
function applyMotion(){
  var reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var paused=motionPaused||reduced||document.hidden;
  if(document.documentElement)document.documentElement.setAttribute('data-motion',paused?'paused':'running');
  var button=document.getElementById('motionToggle');
  button.textContent=reduced?'Movimiento reducido':motionPaused?'Activar movimiento':'Pausar movimiento';
  button.setAttribute('aria-pressed',String(motionPaused||!!reduced));
  button.disabled=!!reduced;
}
function toggleMotion(){motionPaused=!motionPaused;try{window.localStorage.setItem('rhapsod.motion',motionPaused?'paused':'running');}catch(e){}applyMotion();}
function initAmbience(){
  var scene='aurora';
  try{scene=window.localStorage.getItem('rhapsod.scene')||scene;motionPaused=window.localStorage.getItem('rhapsod.motion')==='paused';}catch(e){}
  setScene(scene);applyMotion();
  document.addEventListener('visibilitychange',applyMotion);
  var media=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)');
  if(media&&media.addEventListener)media.addEventListener('change',applyMotion);
}
`;
